---
name: Setup Test Environment
description: Install prerequisites for testing
inputs:
  ENV:
    description: Environment to test against
    required: true
  REQUIREMENTS_FILE:
    description: Requirements file to use
    required: true
runs:
  using: composite
  steps:
    - name: Install system-level dependencies
      shell: bash
      run: |-
        echo "Installing system-level dependencies for ${{ inputs.ENV }}"
        sudo apt-get install -q -y firefox
        echo "Environment ${{ inputs.ENV }} ready to test"
    - name: Install virtualenv
      uses: getsentry/action-setup-venv@v2.0.0
      with:
        python-version: 3.12
        cache-dependency-path: |
          ${{ inputs.REQUIREMENTS_FILE }}
        install-cmd: pip install -r ${{ inputs.REQUIREMENTS_FILE }}
